apiVersion: v1
kind: Service
metadata:
  name: nica-backend
  labels:
    app: nica-backend
spec:
  selector:
    app: nica-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
