apiVersion: v1
kind: Service
metadata:
  name: nica-frontend
  labels:
    app: nica-frontend
spec:
  selector:
    app: nica-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
